name: Deploy Pipeline

on:
  push:
    branches: [ main ]

jobs:
  validate-k8s:
    runs-on: ubuntu-latest
    name: Validar despliegue
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Instalar kubeval
      run: |
        wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
        tar xf kubeval-linux-amd64.tar.gz
        sudo mv kubeval /usr/local/bin

    - name: Validar manifiestos con kubeval
      run: |
        kubeval kubernetes/*.yaml

    - name: Verificar sintaxis de manifiestos con kubectl
      run: |
        kubectl apply --dry-run=client -f kubernetes/ || echo "Errores de sintaxis encontrados."
        echo "Sintaxis verificada."

  build-and-push:
    needs: validate-k8s
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push user-service
      uses: docker/build-push-action@v5
      with:
        context: user-service
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/user-service:latest
          ghcr.io/${{ github.repository_owner }}/user-service:${{ github.sha }}

    - name: Build and push order-service
      uses: docker/build-push-action@v5
      with:
        context: order-service
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/order-service:latest
          ghcr.io/${{ github.repository_owner }}/order-service:${{ github.sha }}

    - name: Build and push inventory-service
      uses: docker/build-push-action@v5
      with:
        context: inventory-service
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/inventory-service:latest
          ghcr.io/${{ github.repository_owner }}/inventory-service:${{ github.sha }}